
name: "Build and publish images"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: markis/cloudflared
  PLATFORMS: linux/arm64,linux/arm/v7,linux/arm/v6

jobs:
  build-and-push:
    name: "Build and publish images"
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch upstream and get latest tag
        id: tags
        run: |
          git remote add upstream https://github.com/cloudflare/cloudflared.git && \
          git fetch --tags upstream && \
          latest_tag=$(git describe --tags "$(git rev-list --tags --max-count=1)") && \
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: >
            GIT_TAG=${{ steps.tags.outputs.latest_tag }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: >
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.tags.outputs.latest_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
